from .types import Deg, Vec


def activate_stage() -> None: ...


class Set:
    @staticmethod
    def roll(x: float) -> None: ...

    @staticmethod
    def pitch(x: float) -> None: ...

    @staticmethod
    def yaw(x: float) -> None: ...

    @staticmethod
    def throttle(x: float) -> None: ...

    @staticmethod
    def brake(x: float) -> None: ...

    @staticmethod
    def slider1(x: float) -> None: ...

    @staticmethod
    def slider2(x: float) -> None: ...

    @staticmethod
    def slider3(x: float) -> None: ...

    @staticmethod
    def slider4(x: float) -> None: ...

    @staticmethod
    def translate_forward(x: float) -> None: ...

    @staticmethod
    def translate_right(x: float) -> None: ...

    @staticmethod
    def translate_up(x: float) -> None: ...

    @staticmethod
    def translation_mode(x: float) -> None: ...


class SetCraft:
    @staticmethod
    def pitch(x: Deg) -> None: ...

    @staticmethod
    def heading(x: Deg) -> None: ...

    @staticmethod
    def pitch_pids(x: Vec) -> None: ...

    @staticmethod
    def roll_pids(x: Vec) -> None: ...


def target_node(name: str) -> None: ...
